name: Terraform Plan
on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Terraform Init & Plan
        run: |
          cd infrastructure/dev
          terraform init
          terraform plan